FROM python:3.8 AS simple_storage

WORKDIR /usr/src/app

RUN python3 -m venv /venv
ENV PATH="/venv/bin:$PATH"
ENV PYTHONPATH="/usr/src/app:$PYTHONPATH"
RUN pip install --upgrade pip

COPY src .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt